### PR TITLE
fix test required libraries

### PR DESCRIPTION
**Pull request by msaf1980**

### CODE REVIEW

**Comment by msaf1980** [comment]
I fix that. 

Also fix test without libeio on MacOS and disable test with embedded libeio only.

**Comment by Lupus** [comment]
Looks good! Are you going to brush up the commits, or we could merge?

**Comment by msaf1980** [comment]
I don't have access to MacOS station, so can't fix MacOS embedded libeio test. So you can merge.

**Comment by Lupus** [comment]
Landed. Thanks once again!

**Pull request merged**
